on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-frontend-to-netlify-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up git authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kjwagner613/nursery_demo_v2.git

      - name: Prepare frontend artifacts
        run: |
          rm -rf temp && mkdir temp
          cp -r frontend/* temp/
          # Optional: add .gitignore or Netlify config if needed
      - name: Clean untracked files
        run: git clean -fdx
      - name: Switch to netlify-frontend branch and copy files
        run: |
          git fetch origin netlify-frontend:netlify-frontend || git checkout --orphan netlify-frontend
          git checkout netlify-frontend
          git rm -rf . || true
          cp -r temp/* .
          git add .
          git commit -m "Update netlify-frontend from master" || echo "No changes to commit"
          git push origin netlify-frontend

  copy-backend-to-heroku-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up git authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kjwagner613/nursery_demo_v2.git

      - name: Prepare backend artifacts
        run: |
          rm -rf temp && mkdir temp
          cp -r backend/* temp/
          # Optional: add .gitignore or Heroku config if needed
      - name: Clean untracked files
        run: git clean -fdx
      - name: Switch to heroku-backend branch and copy files
        run: |
          git fetch origin heroku-backend:heroku-backend || git checkout --orphan heroku-backend
          git checkout heroku-backend
          git rm -rf . || true
          cp -r temp/* .
          git add .
          git commit -m "Update backend from master" || echo "No changes to commit"
          git push origin heroku-backend
