on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  copy-frontend-to-netlify-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare frontend artifacts
        run: |
          rm -rf temp && mkdir temp
          cp -r frontend/* temp/
         
          # Optional: add .gitignore or Netlify config if needed

      - name: Switch to netlify-frontend branch and copy files
        run: |
          git fetch origin netlify-frontend:netlify-frontend || git checkout --orphan netlify-frontend
          git checkout netlify-frontend
          git rm -rf . || true
          cp -r temp/* .
          git add .
          git commit -m "Update netlify-frontend from master" || echo "No changes to commit"
          git push origin netlify-frontend

  copy-backend-to-heroku-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare backend artifacts
        run: |
          rm -rf temp && mkdir temp
          cp -r backend/* temp/
         
          # Optional: add .gitignore or Heroku config if needed

      - name: Switch to heroku-backend branch and copy files
        run: |
          git fetch origin heroku-backend:heroku-backend || git checkout --orphan heroku-backend
          git checkout heroku-backend
          git rm -rf . || true
          cp -r temp/* .
          git add .
          git commit -m "Update backend from master" || echo "No changes to commit"
          git push origin heroku-backend
